services:
  - type: web
    name: kino-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kino_bot.py"
    pythonVersion: 3.11.8
    region: frankfurt
